# Generated by Django 5.1.5 on 2025-01-27 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="item_tags",
            table=None,
        ),
    ]
