# Generated by Django 5.1.5 on 2025-01-28 12:40

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0002_alter_item_tags_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item_Tag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.ImageField(upload_to="items/"),
        ),
        migrations.AddField(
            model_name="item",
            name="items",
            field=models.ManyToManyField(related_name="items", to="ecommerce.item_tag"),
        ),
        migrations.DeleteModel(
            name="Item_Tags",
        ),
    ]
