# Generated by Django 5.1.5 on 2025-01-28 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0003_item_tag_alter_item_image_item_items_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="items",
            new_name="tags",
        ),
    ]
